version: "3.8"

services:
  nextjs:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    env_file:
      - .env
    command: sh -c "npm install && npm run dev"
